[package]
name = "ton_ws_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7", features = ["ws"] }
tonlib-rs = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
dashmap = "5"
